Add condition on tag

diff --git a/.github/workflows/build-test-publish.yaml b/.github/workflows/build-test-publish.yaml
--- a/.github/workflows/build-test-publish.yaml
+++ b/.github/workflows/build-test-publish.yaml
@@ -30,23 +30,22 @@ jobs:
     - name: Test
       run: dotnet test --configuration Release --no-restore --no-build --verbosity normal Optional.Tests
 
-    - name: Extract version from csproj
-      shell: bash
-      run: |
-        Version=$(grep --only-matching --perl-regex '<Version>[0-9]+(\.[0-9]+)*</Version>' Optional/Optional.csproj | grep --only-matching --perl-regex '[0-9\.]+')
-        echo "Version=$Version" | tee --append "$GITHUB_ENV"
-        exit $(test -n "$Version")
-
-    - name: Pack package
-      shell: bash
-      run: dotnet pack Optional --configuration Release --no-build --include-symbols --nologo --output nuget
-
-    - name: Push package
+    - name: Publish on version change
       shell: bash
       env:
         NUGETKEY: ${{ secrets.NUGETKEY }}
-      run: dotnet nuget push nuget/*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key "$NUGETKEY" --skip-duplicate
-
-    - name: Create tag
-      shell: bash
-      run: git tag "$Version" && git push origin "$Version"
+      run: |
+        Version=$(grep --only-matching --perl-regex '<Version>[0-9]+(\.[0-9]+)*</Version>' Optional/Optional.csproj | grep --only-matching --perl-regex '[0-9\.]+')
+        echo "Version=$Version"
+        if test -z "$Version"; then
+          echo 'Could not get version from .csproj'
+          exit 1
+        fi
+        if test -n $(git tag --list "$Version"); then
+          echo "Version $Version already exists"
+          exit 0
+        fi
+        dotnet pack Optional --configuration Release --no-build --include-symbols --nologo --output nuget &&\
+        dotnet nuget push nuget/*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key "$NUGETKEY" --skip-duplicate &&\
+        git tag "$Version" && git push origin "$Version"
+        exit $?
